

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod2
spec:
  acme:
    # enter an email that will receive alters on certificate expiration
    email: alaktif9@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod2-account-key

    solvers:
    - dns01:
        cloudDNS:
          project: ivory-folder-406609
          serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: service_account.json

